### ISSUE TITLE
Creating Vault from CLI & validating data from front end 

### ISSUE THREAD

**Issue by cybertronprime** [comdex-official/comdex#239]
1. Use the same user seeds to log in to the front end.
2. Verify if it goes to the edit page in the front end or not
3. Verify the total collateral locked in the dashboard
4. Verify the ExtendedPairVault data in Vault Mapping
5. Verify the collector, collections
6. Verify the interest function (do the manual calculation as well to check)
7. Check all related queries data 
8. Check all numbers of user balance n match it with existing vault data (numbers should add up)
9. Check stability and draw down fees deductions

**Comment by Subham2804** [comment]
Checked and verified from cli and frontend
