### ISSUE TITLE
Locker testing

### ISSUE THREAD

**Issue by cybertronprime** [comdex-official/comdex#241]
Locker deposit testing
Locker rewards accumulation testing
Locker Mapping Lookup table data testing
Withdrawing rewards from the locker 
Matching numbers 
Reviewing changes in collector values as a reward is distributed. (change will occur per block)
Match all the numbers (when testing locker n collector data, dont create new vaults after checking , else numbers will not match , do the lcoker testing after creating 2-3 vaults to get idea of the numbers )

**Comment by Subham2804** [comment]
Locker deposit testing : No  issue found
Locker rewards accumulation testing : No  issue found
Locker Mapping Lookup table data testing : No issue found
Withdrawing rewards from the locker : No  issue found
Matching numbers : No  issue found
Reviewing changes in collector values as a reward is distributed : No  issue found

Issues Found :
1. Data not getting updated in the query : rewards by product and asset id
   Current issue status: Fixed
   Fixed issue branch : testdev_demo
