### ISSUE TITLE
Converting all proposal to correct format

### ISSUE THREAD

**Issue by cybertronprime** [comdex-official/comdex#242]

**Comment by Subham2804** [comment]
Required contract proposal present in gov contract
https://github.com/comdex-official/gov-contracts/blob/testdev/contracts/governance/src/contract.rs

ESM Proposal pending(binding Dependency)

Current Proposal:
1. add-extended-pair-vault
2. add-collector
3. whitelist-asset-locker
4. activate-locker-rewards
5. activate-vault-interest
6. whitelist-app-for-liquidation
7. set-auction-mapping-for-asset
8. update-lsr
9. update-extended-pair
10. deactivate-stability-fee-for-app
11. remove-whitelist-app-for-liquidation
12. set-auction-params
13. ESM(pending)

**Comment by cgsingh33** [comment]
completed

**Comment by cybertronprime** [comment]
Please add a list segregated by base and contract
