### ISSUE TITLE
Duplicate Asset name allowed 

### ISSUE THREAD

**Issue by karthik340** [comdex-official/comdex#340]
Duplicate asset name shouldnt be allowed
function  : assetKeeper.AddAssetRecords(*ctx, tc.msg)
data :
{"Add Asset cmdx ucmdx",
			assetTypes.Asset{Name: "CMDX",
				Denom:     "ucmdx",
				Decimals:  1000000,
				IsOnChain: true},
			false,
		},
		{"Add Asset:  Duplicate Asset Name  2 cmdx uosmo",
			assetTypes.Asset{Name: "CMDX",
				Denom:     "uosmo",
				Decimals:  1000000,
				IsOnChain: true},
			true,
		},

**Comment by cgsingh33** [comment]
we can't have duplicate denoms, but asset names are only for representation. we only use denoms for our logics in the app, not asset names.
@pratikasr  can also confirm

**Comment by dheerajkd30** [comment]
The second asset will be logically incorrect, though. Denoms are what would matter here most. But we should add a check to restrict duplicate names too, to avoid confusion.

**Comment by cgsingh33** [comment]
fixed in v4.1.0
