### ISSUE TITLE
2 governance tokens for single app

### ISSUE THREAD

**Issue by karthik340** [comdex-official/comdex#341]
function : assetKeeper.AddAppRecords(*ctx, tc.msg)
data : 
assetTypes.AppData{
				Name:             "cswap",
				ShortName:        "cswap",
				MinGovDeposit:    sdk.NewIntFromUint64(10000000),
				GovTimeInSeconds: 900,
				GenesisToken: []assetTypes.MintGenesisToken{
					{
						3,
						&genesisSupply,
						true,
						userAddress1,
					},
					{
						2,
						&genesisSupply,
						true,
						userAddress1,
					},
				},
			},

**Comment by cgsingh33** [comment]
Check is added for this.
Hence, not an issue
