### ISSUE TITLE
same asset can be added as genesis token in multiple apps

### ISSUE THREAD

**Issue by karthik340** [comdex-official/comdex#342]
function : assetKeeper.AddAppRecords(*ctx, tc.msg)
error : same asset shouldnt be added as genesis token in multiple apps
data :

assetTypes.AppData{
				Name:             "cswap",
				ShortName:        "cswap",
				MinGovDeposit:    sdk.NewIntFromUint64(10000000),
				GovTimeInSeconds: 900,
				GenesisToken: []assetTypes.MintGenesisToken{
					{
						3,
						&genesisSupply,
						true,
						userAddress1,
					},
					{
						2,
						&genesisSupply,
						true,
						userAddress1,
					},
				},
			},

assetTypes.AppData{
				Name:             "commodo",
				ShortName:        "commodo",
				MinGovDeposit:    sdk.NewIntFromUint64(10000000),
				GovTimeInSeconds: 900,
				GenesisToken: []assetTypes.MintGenesisToken{
					{
						3,
						&genesisSupply,
						true,
						userAddress1,
					},
				},
			},

**Comment by cgsingh33** [comment]
Check is added for this, hence not an issue.
