### ISSUE TITLE
Duplicate app name allowed

### ISSUE THREAD

**Issue by karthik340** [comdex-official/comdex#344]
function : assetKeeper.AddAppRecords(*ctx, tc.msg)

data : 
{
			"Add App cswap cswap",
			assetTypes.AppData{
				Name:             "cswap",
				ShortName:        "cswap",
				MinGovDeposit:    sdk.NewIntFromUint64(10000000),
				GovTimeInSeconds: 900,
				GenesisToken: []assetTypes.MintGenesisToken{
					{
						3,
						&genesisSupply,
						true,
						userAddress1,
					},
					{
						2,
						&genesisSupply,
						true,
						userAddress1,
					},
				},
			},
			1,
			false,
		},
		{
			"Add Duplicate App name cswap werd",
			assetTypes.AppData{
				Name:             "cswap",
				ShortName:        "werd",
				MinGovDeposit:    sdk.NewIntFromUint64(10000000),
				GovTimeInSeconds: 900,
				GenesisToken: []assetTypes.MintGenesisToken{
					{
						3,
						&genesisSupply,
						true,
						userAddress1,
					},
				},
			},
			2,
			true,
		},

**Comment by cgsingh33** [comment]
Issue is fixed Development branch
