### ISSUE TITLE
Asset doesn't exist but app gets added still 

### ISSUE THREAD

**Issue by karthik340** [comdex-official/comdex#346]
error : Asset ID 4 doesnt exist but able to add it in mint genesis token
function :
assetKeeper.AddAppRecords(*ctx, tc.msg)

data : 

{
			"Add App commodo commodo",
			assetTypes.AppData{
				Name:             "sake",
				ShortName:        "sake",
				MinGovDeposit:    sdk.NewIntFromUint64(10000000),
				GovTimeInSeconds: 900,
				GenesisToken: []assetTypes.MintGenesisToken{
					{
						4,
						&genesisSupply,
						true,
						userAddress1,
					},
				},
			},
			3,
			false,
		},

**Comment by cgsingh33** [comment]
There is a check for this at the time of adding assets in-app. 
Not an issue
