### ISSUE TITLE
go version error

### ISSUE THREAD

**Issue by Kwaskoff** [comdex-official/comdex#803]
I try "make install"
```
:~/comdex$ go version
go version go1.20.5 linux/amd64
:~/comdex$ make install
ERROR: Please upgrade Go version to 1.19+
exit 1
make: *** [Makefile:99: check_version] Error 1
```

debian 11, x86

**Comment by zuko-firelord** [comment]
Debug the GO_MINOR_VERSION Calculation, run this command:
go version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -f2

**Comment by zuko-firelord** [comment]
> I try "make install"
> 
> ```
> :~/comdex$ go version
> go version go1.20.5 linux/amd64
> :~/comdex$ make install
> ERROR: Please upgrade Go version to 1.19+
> exit 1
> make: *** [Makefile:99: check_version] Error 1
> ```
> 
> debian 11, x86

Debug the GO_MINOR_VERSION Calculation, run this command:
go version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -f2

**Comment by dheerajkd30** [comment]
This error is now resolved in new version. Let me know if you get it .
